use std::{fmt, str::FromStr};

use anyhow::{Error, anyhow};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct CustomerInput {
    pub name: String,
    pub email: String,
}

#[derive(Serialize, Deserialize)]
pub struct Address {
    city: Option<String>,
    country: Option<String>,
    line1: Option<String>,
    line2: Option<String>,
    postal_code: Option<String>,
}

#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CurrencyCode {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BOV,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BZD,
    CAD,
    CDF,
    CHE,
    CHF,
    CHW,
    CLF,
    CLP,
    CNY,
    COP,
    COU,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MXV,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLE,
    SOS,
    SRD,
    SSP,
    STN,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    USN,
    UYI,
    UYU,
    UYW,
    UZS,
    VED,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XCD,
    XDR,
    XOF,
    XPF,
    YER,
    ZAR,
    ZMW,
    ZWG,
}

#[derive(Serialize, Deserialize)]
pub struct CustomerOutput {
    pub id: String,
    pub name: String,
    pub email: Option<String>,
    address: Option<Address>,
    balance: i64,
    created: i64,
    currency: Option<CurrencyCode>,
    customer_account: Option<String>,
    default_source: Option<String>,
    description: Option<String>,
    livemode: bool,
    phone: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct PaymentMethodOutput {
    pub id: String,
    livemode: bool,
    r#type: StripePaymentMethod,
}

#[derive(Serialize, Debug, Clone, Copy, PartialEq, Deserialize)]
pub enum StripePaymentMethod {
    Boleto,
    Card,
    Paypal,
    Pix,
    SamsungPay,
}
// Implement the Display trait
impl fmt::Display for StripePaymentMethod {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            StripePaymentMethod::Boleto => write!(f, "boleto"),
            StripePaymentMethod::Card => write!(f, "card"),
            StripePaymentMethod::Paypal => write!(f, "paypal"),
            StripePaymentMethod::Pix => write!(f, "pix"),
            StripePaymentMethod::SamsungPay => write!(f, "samsung_pay"),
        }
    }
}
impl FromStr for StripePaymentMethod {
    type Err = Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "boleto" => Ok(StripePaymentMethod::Boleto),
            "card" => Ok(StripePaymentMethod::Card),
            "paypal" => Ok(StripePaymentMethod::Paypal),
            "pix" => Ok(StripePaymentMethod::Pix),
            "samsung_pay" => Ok(StripePaymentMethod::SamsungPay),
            _ => Err(anyhow!("Unknown StripePaymentMethod: {}", s)),
        }
    }
}
